### ISSUE TITLE
Update README?

### ISSUE THREAD

**Issue by rogermc2** [charlie5/swig4ada#1]
The current README file appears to be copied directly fro swig and doesn't give instructions for building swig4ada.
In particular it says to use ./configure but the swig4ada distribution contains no configure file.
Apparently build_gnat_swig should be used. This need to be stated in a swig4ada README file.

**Comment by charlie5** [comment]
Agreed.

I will fix this shortly.

**Comment by rogermc2** [comment]
Thanks

**Comment by charlie5** [comment]
No probs, I appreciate the interest.

I am on freenode irc #ada, if you prefer to chat direct (a polite ada chat group).
